spring.application.name=post-service

spring.datasource.url=jdbc:postgresql://localhost:3001/ig-post-db
spring.datasource.username=ig-post-user
spring.datasource.password=post-password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
